apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: heimdall-cluster
  region: us-east-1
  version: "1.31"

# CRITICAL: We disable the expensive NAT Gateway.
# This forces the nodes to live in Public Subnets, which is simpler.
vpc:
  nat:
    gateway: Disable

managedNodeGroups:
  - name: heimdall-ng-1
    instanceType: t3.medium
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: false